### ISSUE TITLE
Unable to open other files. with Live Server apart from index.html

### ISSUE THREAD

**Issue by ngamsomset** [hqjs/vscode-hq-live-server#5]
Hey!!

I came up with an issue that I can't open other files apart from index.html with the live server. The root file that got run will always be index.html. The others file could be open but can't be live reloaded.

 Does any possible way to  open other file .html say about.html/contact.html with live server? 

thanks !!

**Comment by hqjs** [comment]
Hey, thanks for the reporting. HQ Live Server was designed to open `main` file specified in `package.json` or `index.html`. 
Other files still can be opened by modifying URL in the browser, but livereload script is only attached to `index.html`.

It is worth to try [LiveReload plugin for Chrome](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei/related) it might help to reload pages different from `index.html`, but it needs to be tested. I will think of the safe way to attach lievereload to every `html` page, but it's not trivial task.

Regarding opening active file from the editor - it might be confusing as VSCode limits you with text files only and AFAIK it won't be possible to open images the same way (you will still have to modify browser URL). But it sounds like a good idea in general, it might worth to implement it for `.html` files only and put it under configuration.

**Comment by ngamsomset** [comment]
Thank you so much for your support!!
