### ISSUE TITLE
Error and Bug Report

### ISSUE THREAD

**Issue by tracure1337** [hqjs/vscode-hq-live-server#6]
Hi,

The extension works flawlessly in Ubuntu 20.04 and MacOS Catalina but I have problems getting it to work in Windows 10.

Node.js is installed version 12.18.2

I tried the Debugger option and the command line option but none of them work for me unfortunately.

I get the error message as visible on the screenshot.

I attached a second screenshot as there is a difference between the number of backslashes in the example.

In the github readme it is:
Examples:
chrome --incognito --headless --remote-debugging-port=9222
C:\Program Files\Firefox Developer Edition\firefox.exe --private-window

but in the extension settings text it is:

Examples : 
chrome --incognito --headless --remote-debugging-port=9222 
C:\\Program Files\\Firefox Developer Edition\\firefox.exe --private-window

![Ft](https://user-images.githubusercontent.com/43231640/87512865-0cb84700-c678-11ea-8e8e-e1c8feff2499.PNG)
![TT](https://user-images.githubusercontent.com/43231640/87512869-0d50dd80-c678-11ea-8b14-7e480ead3c7b.PNG)

**Comment by tracure1337** [comment]
Okay, for some reason a full restart of the system fixed it. Windows debugging 😄 

The typo hopefully get`s fixed tho.

**Comment by hqjs** [comment]
Fixed in `0.0.9`
