### ISSUE TITLE
code get inject by live-server 

### ISSUE THREAD

**Issue by johnbolo-coder** [hqjs/vscode-hq-live-server#7]
code get inject by live-server can you tell how to fix it

**Comment by hqjs** [comment]
Can you please explain the issue in more details? I don't get what's the problem.

**Comment by hqjs** [comment]
`HQ Live Server` inject `hq-liverolad.js` script during development to provide reloading functionality. Here is what the code looks like:
```js
const socket = new WebSocket(`ws${location.protocol === 'https:' ? 's' : ''}://${location.host}`);

socket.addEventListener('message', event => {
  if (event.data === 'reload') window.location.reload();
});

```

What it does - connects to `hq` websocket server and listens for `reload` event that is being fired when you're changing your files.

When you building the project with `hq` - it creates `hq-sw.js` file with the service worker caching the list of static files in your project and adds initialization of this worker to your `index.html`. You can modify or remove the initialisation or the worker based on your needs.

Hope that helps. Please reopen the issue if it is not answers your question.
