### ISSUE TITLE
Server won't Start - build in continual loop

### ISSUE THREAD

**Issue by AverTry** [hqjs/vscode-hq-live-server#9]
Original comments:

I cannot find any forum or troubleshooting, so I have to comment here, I don't want to rate, as I haven't tested. Almost clean install of VS Code, updated to Node 12.18 but HQ will not load a page and clicking build constantly runs with no end. I have disabled ALL extensions, done restarts, isolated my work, shut down other local servers(Laragon), tried on a starting template - basic html. I could use your competitor, but I would like it running inside vs code. main reason for a combined browser console view, if that's even possible. I know I can window side by side, but it's a trip and other console plugins are equally lacking. So if you know how to get it fully working, I would be most thankful.
PS. will change rating, after fix, as I cannot post without one.
Reply:
Hi, thanks for trying the extension. I would be happy to help to fix the issues. Can you please follow Github link https://github.com/hqjs/vscode-hq-live-server/issues and create an issue there. A bit more details required - your OS, project details, may be some code samples would be really helpful.

Ok thanks for answering I have windows 10 fully up to date. Uninstalled everything and reinstalled. But no joy!
Project details are meaningless in this case as, the server won't start for anything, no browser opens, no preview starts, nothing gets built, no files are created? Unless there is some leftover configuration that's causing the conflict, I don't know what to suggest?

**Comment by hqjs** [comment]
Thanks for reporting. Build problem for windows is known issue, that was recently reported, but serving files should work. Any error messages that you see in a console?

**Comment by AverTry** [comment]
The only issue that came up was node being v 11, that comes with vs code. after update that went away. The only thing that came to mind was, would it have worked if node was up to date prior to installing hq. and that maybe something leftover is causing the issue. I don't have time to fresh install everything, like in virtual env to test?

**Comment by hqjs** [comment]
Did you install node with `nvm` or just download the binary from the website? Can you please try to install `@hqjs/hq` package from `npm` and run it in the root of your project?
1. Make sure you have node >= 12.10 installed as a default
```sh
node -v
```
2. Install `hq` globally
```sh
npm i -g @hqjs/hq
```
3. in the project root run `hq` in verbose mode
```sh
hq --verbose
```
4. Follow the link in the console and past the output to the issue.

**Comment by AverTry** [comment]
```

Microsoft Windows [Version 10.0.18363.1082]
(c) 2019 Microsoft Corporation. All rights reserved.
Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink


10:35:36.58 | C:\Laragon-PC\www\Classes>npm i -g @hqjs/hq
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\Admin\AppData\Roaming\npm\hq -> C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\run.js

> node-sass@4.14.1 install C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-x64-72_binding.node
Download complete .] - :
Binary saved to C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\node-sass\vendor\win32-x64-72\binding.node
Caching binary to C:\Users\Admin\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-72_binding.node

> core-js@2.6.11 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> gifsicle@5.1.0 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> mozjpeg@7.0.0 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\mozjpeg
> node lib/install.js

  √ mozjpeg pre-build test passed successfully

> pngquant-bin@6.0.0 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\pngquant-bin
> node lib/install.js

  √ pngquant pre-build test passed successfully

> core-js@3.6.5 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> node-sass@4.14.1 postinstall C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\node-sass\vendor\win32-x64-72\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\@hqjs\hq\node_modules\@babel\cli\node_modules\chokidar\node_modules\fsevents):    
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\@hqjs\hq\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\@hqjs\hq\node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @hqjs/hq@0.0.26
added 1431 packages from 546 contributors in 115.388s
```
That's the install of hq, lots of depreciated values.
Didn't see any verbose output, See Screenshots...
All steps done within vs code and browser preview extension.

![image](https://user-images.githubusercontent.com/72357571/95066200-f8756a80-06f9-11eb-961a-863ec41b4381.png)
![image](https://user-images.githubusercontent.com/72357571/95066257-117e1b80-06fa-11eb-809e-f5f2f784c9d4.png)

**Comment by hqjs** [comment]
It hangs somewhere between lines 84 and 94 in `server.mjs`. Can you post the content of the folder `C:\Laragon-PC\www\Classes`
```sh
dir
```

**Comment by AverTry** [comment]
I've tried it on a simple bootstrap4 template in a desktop dir, same issue, nothing to do with contents. All other live plugins work, except the chrome devtools plugin, loads blank. So there maybe something with what's installed, or leftover. I will try on a clean system when I get time. Thanks for your help.

My main issue, I was trying to solve was another way to use internal vscode debuging and preview. Which Browser Preview gives via Chrome Headless, but it's a poor replica of the actual browser. Colors are wrong, blurryness and stretching. I did get close using `just html preview` but the debug console feedback gave back a different sessions results. So my real issue is with Chrome. Guess I'll have to keep lining up the windows side by side, every time I open. 
If you ever find a non chrome headless solution, that would be gold.

**Comment by hqjs** [comment]
I think server hangs as it suppose to log more info in verbose mode, and I don't see this info on your screenshot. My guess is it might fail on finding `package.json` in the folder and may be it creates a loop somewhere. I don't have windows system to check and there were no complains on that from other users, so hard to tell what is wrong. If you can - please debug `server.mjs` or add couple of `console.log` commands to understand when it hangs. On line `94` it suppose to print something similar to
```sh
| hq root    : /Users/yuri/web/hq

| root       : /Users/yuri/web/hqjs.github.io
| src        : .

| certs      :

| babelrc    : undefined
| postcssrc  : undefined
| posthtmlrc : undefined
```

**Comment by AverTry** [comment]
Tried on a new system, and cannot get it to work, not even the build fails to shows and loop?
So maybe I'm doing it wrong.
The Node install was from downloading the exe, and I did not install with the extra tools like python & choclatey.

**Comment by hqjs** [comment]
Let's try to run server by itself first without VScode plugin. What is exact output of `node -v` and `hq --verbose` commands? What if you create `package.json` with `npm init -y` command?

**Comment by AverTry** [comment]
![image](https://user-images.githubusercontent.com/72357571/95303496-27ffb080-087b-11eb-9903-55c6b493765f.png)
![image](https://user-images.githubusercontent.com/72357571/95303598-4cf42380-087b-11eb-8649-de9276cde072.png)

**Comment by hqjs** [comment]
Hmmm, did you stop the server or it quits by itself? The first time you've posted output it was different.

**Comment by hqjs** [comment]
I'd recommend not to do anything at `system32` folder. You'd better cd to the folder with your project.

**Comment by hqjs** [comment]
@AverTry Can you please enter the project directory, then run `hq --verbose` and post exact output of this command without stopping the server. I need to know if it quits by itself or it just freezes somewhere. Then it would be nice to see the content of the folder - output of `dir` command. Then I'd recommend to try to create `package.json` in the project folder with `npm init -y` command (no need to post output of this command) and rerun `hq --verbose` and check if anything changes.

**Comment by AverTry** [comment]
Inside vscode testing new dropdown select type controls. Nothing in-depth, has the same output on any project.
![image](https://user-images.githubusercontent.com/72357571/95574166-71d7ca80-0a24-11eb-8ced-f41eb8efe117.png)
With vscode closed and with an admin cmd console
![image](https://user-images.githubusercontent.com/72357571/95574581-1528df80-0a25-11eb-9ebf-64181158f08b.png)
Now we are getting somewhere. Sorry last time I did it in winsys dir.
![image](https://user-images.githubusercontent.com/72357571/95575086-0131ad80-0a26-11eb-95d4-3ff90cabc417.png)

**Comment by AverTry** [comment]
The whole browser output should have rendered in the code tags,

**Comment by AverTry** [comment]
![image](https://user-images.githubusercontent.com/72357571/95575920-794ca300-0a27-11eb-81dc-9b0a196402ba.png)
Ok so it now works inside of vs-code, Thanks for that, but why does the npm need to be run inside of the working folder, because you do state zero configuration, or am I missing something?
Also, it's not displaying the page unless I add the /index.html
![image](https://user-images.githubusercontent.com/72357571/95576727-d72dba80-0a28-11eb-8d87-777d8e059baa.png)

**Comment by hqjs** [comment]
It seems like it fails with `package.json` on windows when it does not exists. On UNIX it works in both cases. I should fix that, but now at least I know where to look. To get rid of `/index.html` in the url - point `main` field in `package.json` to that file, by default it is pointed to `index.js`. Thanks a lot for assistance, I'll try to find a fix for windows and hope you will be able to help with the testing.

**Comment by AverTry** [comment]
Sure, no problem. And Thank you!

**Comment by hqjs** [comment]
Hey @AverTry can you please try `hq@0.0.28`? It should fix the problem with `package.json` and hopefully windows build as well. If it works - I will update the plugin.

**Comment by AverTry** [comment]
Normal live part is fine, but the build couldn't find something, it's probably something on my end as I'm only a beginner at this node stuff, and vscode. i ran it against my only project on github, so easy for you to check it on other OS. But at least it didn't hang in a continual loop, that's a plus.

`
Terminal Output:



Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.
Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink


13:48:03.97 | C:\Laragon-PC\www\Classes>hq
(c) hqjs @ 0.0.28
Start time: 0.5 s

Visit http://localhost:8080
or http://192.168.0.13:8080 within local network

^CTerminate batch job (Y/N)? ^C

13:54:01.58 | C:\Laragon-PC\www\Classes>hq build
(c) hqjs @ 0.0.28
Start time: 0.5 s

Visit http://localhost:8080
or http://192.168.0.13:8080 within local network

⬇️  /index.html

TypeError: Cannot read property 'join' of undefined
    at file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@hqjs/hq/crawl/html.mjs:66:44
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:91:45
    at traverse (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:105:26)        
    at traverse (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:111:5)
    at traverse (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:105:17)        
    at traverse (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:111:5)
    at traverse (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:105:17)        
    at Array.match (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\api.js:90:7)       
    at tree.match.tag (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@hqjs/hq/crawl/html.mjs:40:12)
    at err (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\posthtml\lib\index.js:217:34)

⬇️  /C:/Laragon-PC/www/Classes/favicon.ico
⬇️  /C:/Laragon-PC/www/Classes/style.css
⬇️  /C:/Laragon-PC/www/Classes/myScript.js

� /C:/Laragon-PC/www/Classes/favicon.ico

� /C:/Laragon-PC/www/Classes/style.css

� /C:/Laragon-PC/www/Classes/myScript.js

⬇️  /C:/node_modules/core-js/modules/es.array.index-of

❌ Error /C:/node_modules/core-js/modules/es.array.index-of: File /C:/node_modules/core-js/modules/es.array.index-of not found


NotFoundError: File /C:/node_modules/core-js/modules/es.array.index-of not found
    at Object.throw (C:\Users\Admin\AppData\Roaming\npm\node_modules\@hqjs\hq\node_modules\koa\lib\context.js:97:11)      
    at resolveSrc (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@hqjs/hq/middlewares/resolve-path.mjs:128:21)  

Error: Unable to build /C:/node_modules/core-js/modules/es.array.index-of: Not Found
    at build (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@hqjs/hq/crawl/index.mjs:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async request (file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/@hqjs/hq/crawl/index.mjs:115:5)

`

**Comment by hqjs** [comment]
@AverTry thanks for testing. There is still bug with the build on windows, I'm trying to find the issue with the other guy who has windows machine. Did you try to run the project without trick with `package.json` that should be fixed.

**Comment by AverTry** [comment]
I don't know what that is, do you mean outside of vscode?

**Comment by hqjs** [comment]
I mean to make it work we had to create `package.json` file with `npm init -y` command and now that is fixed. You can try to remove `packgae.json` and check if it still works.

**Comment by AverTry** [comment]
Yeah, I guess it does, as I have no need for node in that project. So no package.json was there during the test.

**Comment by hqjs** [comment]
Awesome, thanks! I'll keep you posted on the progress with windows build.

**Comment by hqjs** [comment]
@AverTry can you please try the latest version of both plugin and server?

**Comment by hqjs** [comment]
Closed because of inactivity, should work for now.
